version: '3.7'

# Networks
networks:
  # Internal network
  internal:
    driver: bridge

# Volumes
volumes:
  # MySQL volume
  mysql_data:
    driver: local
  # Redis volume
  redis_data:
    driver: local

# Services
services:

  # MySQL
  mysql:
    image: mysql:5.7
    container_name: mysql
    networks:
      - internal
    volumes:
      - .:/var/www/app
      - mysql_data:/var/lib/mysql
    working_dir: /var/www/app
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - "3306:3306"

  # Nginx
  nginx:
    image: webdevops/php-nginx:8.2
    container_name: nginx
    networks:
      - internal
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    volumes:
      - .:/var/www/app
    working_dir: /var/www/app
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/app/public
      - PHP_DATE_TIMEZONE=UTC
      - PHP_DISPLAY_ERRORS=0
      - WEB_DOCUMENT_INDEX=index.php
    expose:
      - 9090
    ports:
      - "8080:80"

  # Redis
  redis:
    image: redis:6
    container_name: redis
    command: --append only yes
    networks:
      - internal
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
